title: Geo-Information
author: Chair of Cartography and Visual Analytics
execute:
  execute_notebooks: "off"
html:
  baseurl: /Geo-Information/
  favicon: images/TUM.png
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  collapse_navigation: false
  show_navbar_depth: 3
  expand_subsections: true
  show_toc_level: 3
  use_multitoc_numbering: true

sphinx:
  config:
    copyright: "2025"
    myst_links_external_new_tab: true
    html_show_sourcelink: false
    html_sidebars:
      "**": ["navbar-logo.html", "search-field.html", "sbt-sidebar-nav.html"]
    html_theme_options:
      navigation_depth: 4
      collapse_navigation: false
      expand_subsections: true
      footer_items: ["copyright", "powered-by"]

repository:
  url: https://github.com/KhanLiu/Geo-Information
  path_to_book: ""
  branch: main